name: S3 Cache Action
description:
    Allows to skip a job if it already succeeded for the same repo state. Uses S3 for caching.
author: Pleo OSS
inputs:
    bucket_name:
        description:
            Name of the S3 bucket to use for storing cache files. The job needs to have AWS
            credentials configured to allow read/write from this bucket.
        required: true
    key_prefix:
        description:
            Key prefix to add to the cache files key. By default the job ID is used. The full key
            used for the cache files is "cache/${repoOwner}/${repoName}/${keyPrefix}/${treeHash}"
        default: ${{ github.job }}
        required: false
outputs:
    processed:
        description: Indicates if the job has already been performed for the current repo tree hash
    hash:
        description: The repo tree hash which was used for caching
runs:
    using: node16
    main: dist/restore/index.js
    post: dist/save/index.js
    post-if: success()
