name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        name: Run "Release Please"
        runs-on: ubuntu-22.04
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  release-type: node
                  package-name: '@pleo-oss/s3-cache-action'
